version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: "on-failure"
    environment:
      APPLICATION_ENV: $APPLICATION_ENV
      DEVELOPER_ENV: $DEVELOPER_ENV
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: $MYSQL_PORT
    volumes:
      - "./:/srv/www"
      - "./build/docker/apache.conf:/etc/apache2/conf-enabled/zz_dvusd_dev.conf"
    depends_on:
      - mysql
    ports:
      - "80:80"
    networks:
      - shared
  mysql:
    build:
      context: ./
      dockerfile: build/docker/compose/mysql/Dockerfile
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - "3307:3306"
    networks:
      - shared

networks:
  shared:
    external: true

volumes:
  mysql_data:

###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
